# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["dataprep.py"]

doc_url = "https://iskode.github.io/acdc/"

git_url = "https://github.com/iskode/acdc/tree/master/"

def custom_doc_links(name): return None
