# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"MRImage": "00_core.ipynb",
         "MRImageSegment": "00_core.ipynb",
         "loadnii": "00_core.ipynb",
         "open_mri": "00_core.ipynb",
         "open_mri_mask": "00_core.ipynb",
         "MRImageList": "00_core.ipynb",
         "MRImageSegLabelList": "00_core.ipynb"}

modules = ["dataprep.py"]

doc_url = "https://iskode.github.io/acdc/"

git_url = "https://github.com/iskode/acdc/tree/master/"

def custom_doc_links(name): return None
