# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"resize_slices": "00_dataprep.ipynb",
         "apply_trans": "00_dataprep.ipynb",
         "MRImage": "00_dataprep.ipynb",
         "MRImageSegment": "00_dataprep.ipynb",
         "loadnii": "00_dataprep.ipynb",
         "open_mri": "00_dataprep.ipynb",
         "open_mri_mask": "00_dataprep.ipynb",
         "MRImageList": "00_dataprep.ipynb",
         "MRImageSegLabelList": "00_dataprep.ipynb",
         "MRISegItemList": "00_dataprep.ipynb",
         "to_images": "01_model.ipynb",
         "to_mri": "01_model.ipynb",
         "MyDynamicUnet": "01_model.ipynb",
         "unet4mri_learner": "01_model.ipynb"}

modules = ["dataprep.py",
           "model.py"]

doc_url = "https://iskode.github.io/acdc/"

git_url = "https://github.com/iskode/acdc/tree/master/"

def custom_doc_links(name): return None
